added error checking

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -52,8 +52,6 @@ jobs:
             "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.login-aws-ecr.outputs.registry }}"
           ]' --query "Command.CommandId" --output text)
 
-          echo "$command_id"
-
           aws ssm wait command-executed \
           --command-id $command_id \
           --instance-id i-0d3eafea510bc4681
@@ -66,4 +64,6 @@ jobs:
             echo "Command executed Successfully"
           else 
             echo "Command failed"
+            echo "Error: $status"
+            exit 1
           fi
